"""participation_notes_car_racetype

Revision ID: 145c3a5db8dc
Revises: 4c89be129b0c
Create Date: 2026-06-11 21:10:49.811295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '145c3a5db8dc'
down_revision: Union[str, Sequence[str], None] = '4c89be129b0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codice', sa.String(length=20), nullable=False),
    sa.Column('descrizione', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice')
    )
    op.create_index(op.f('ix_race_types_id'), 'race_types', ['id'], unique=False)
    op.add_column('participations', sa.Column('nota_personale', sa.Text(), nullable=True))
    op.add_column('participations', sa.Column('con_macchina', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participations', 'con_macchina')
    op.drop_column('participations', 'nota_personale')
    op.drop_index(op.f('ix_race_types_id'), table_name='race_types')
    op.drop_table('race_types')
    # ### end Alembic commands ###
